spring.application.name=dream-shops
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=dreamShop;encrypt=true;trustServerCertificate=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
